stages:
- build

daemonless:
  stage: build
  image:
    name: moby/buildkit:rootless
    entrypoint: [ "buildctl-daemonless.sh" ]
  variables:
    BUILDKITD_FLAGS: --oci-worker-no-process-sandbox
  script:
  - |
    build \
        --frontend=dockerfile.v0 \
        --local context=. \
        --local dockerfile=.
  tags:
  - generic
